### ISSUE TITLE
Usage In Teensy Audio Library

### ISSUE THREAD

**Issue by barcesat** [greiman/UsbFat#1]
Hello @greiman ,
Thanks for your so easy to use library!

I've managed to run it on a Teensy 3.1 board and read files on a USB Memory Stick with it.
However, I want to read WAV files and play them using the Teensy Audio library: https://github.com/PaulStoffregen/Audio .

There's an example there utilizing SD card: https://github.com/PaulStoffregen/Audio/blob/master/examples/WavFilePlayer/WavFilePlayer.ino

I want to do the same but using your library but haven't managed to get the File commands right. Do you think you can help me with that?
Thanks,
Ziv

**Comment by greiman** [comment]
I get many requests like this daily so I can’t help.

From: barcesat 
Sent: Sunday, April 19, 2015 4:12 PM
To: greiman/UsbFat 
Cc: Bill Greiman 
Subject: [UsbFat] Usage In Teensy Audio Library (#1)

Hello @greiman ,
Thanks for your so easy to use library!

I've managed to run it on a Teensy 3.1 board and read files on a USB Memory Stick with it.
However, I want to read WAV files and play them using the Teensy Audio library: https://github.com/PaulStoffregen/Audio .

There's an example there utilizing SD card: https://github.com/PaulStoffregen/Audio/blob/master/examples/WavFilePlayer/WavFilePlayer.ino

I want to do the same but using your library but haven't managed to get the File commands right. Do you think you can help me with that?
Thanks,
Ziv

**Comment by greiman** [comment]
closed
