### ISSUE TITLE
Problem with the library on the Mega 2560 

### ISSUE THREAD

**Issue by myslivec** [greiman/UsbFat#16]
Thanks for the super library!  

I tested the library UsbFat on the board Arduino Uno and it worked. The problem is on the board Arduino Mega 2560, initialization is unsuccessful (Error: initUSB). 

For SS I use pin 53.  Miso, Mosi, SCL standardly 50, 51, 52. The sketch is same as example UsbLogger. Arduino IDE 2.0.0

Please, do you have any idea why it doesn't work?

Thanks. Tomas

**Comment by greiman** [comment]
I have no idea.  I have not looked at this library in eight years.  Are you sure your USB adapter is connected to the correct SPI pins. 

I did try using the current SdFat library with a USB key and I think some people have found [this post](https://github.com/greiman/UsbFat/issues/7#issuecomment-1176252273) and are using SdFat V2.

**Comment by myslivec** [comment]
Ok, thanks. The connection for SPI is correct, I checked the post with SdFat V2, changed USB flash disc and the error is key.begin now. USB state: 90.

**Comment by greiman** [comment]
Which USB shield/module are you using on the mega and how is it wired?

**Comment by myslivec** [comment]
I use this module https://chome.nerpa.tech/mcu/usb-host-mini-hardware-manual
The connection with Mega is SS -> pin 53, MOSI -> pin 51, MISO -> pin 50 and SCK -> pin 52. Power is 5V for USB flesh disc, for MAX is 3,3V. 
I tried change pins in the UsbCore.h for Arduino Mega from P10 to P53, but the error with the key begin still appears.

**Comment by greiman** [comment]
I don't have that module.

I do have an old [Arduino ADK](https://docs.arduino.cc/retired/boards/arduino-mega-adk-rev3) which is a Mega2560 with a USB interface.  USB_Host_Shield_2.0 supports it.

I tried it and it works.  Here is output from the unmodified UsbKey.ino:

> Type any character to start
> Host initialized, ms: 1003
> USB powered, ms: 1003
> USB state: 20, ms: 1008
> USB state: 40, ms: 1204
> USB state: 50, ms: 1254
> USB state: 51, ms: 1254
> USB state: 90, ms: 6702
> 2022-01-01 00:00         22 usbtest.txt

Only change was to SdFatConfig.h:
`#define USE_BLOCK_DEVICE_INTERFACE 1 // 0`

The ADK uses the standard Mega2560  SPI pins and number of other pins:

> Digital: 7 (RST), 50 (MISO), 51 (MOSI), 52 (SCK).
> NB:Please do not use Digital pin 7 as input or output because is used in the communication with MAX3421E
> Non broken out on headers: PJ3 (GP_MAX), PJ6 (INT_MAX), PH7 (SS).

I have no idea how your interface should be connected to the Mega 2560. You could try an issue [here](https://github.com/felis/USB_Host_Shield_2.0).

**Comment by greiman** [comment]
I just tried this [USB Host Shield](https://www.amazon.com/LM-YN-Arduino-Support-Android/dp/B0777DR3T6) on a Mega 2560 and it worked with no mods.  I think only the SPI pins are used on the ISP and pins D9 and D10.

Build:

> Sketch uses 32886 bytes (12%) of program storage space. Maximum is 253952 bytes.
> Global variables use 1274 bytes (15%) of dynamic memory, leaving 6918 bytes for local variables. Maximum is 8192 bytes.

Serial Monitor:

> Type any character to start
> Host initialized, ms: 1003
> USB powered, ms: 1003
> USB state: 20, ms: 1008
> USB state: 40, ms: 1203
> USB state: 50, ms: 1253
> USB state: 51, ms: 1253
> USB state: 90, ms: 6701
> 2022-01-01 00:00         33 usbtest.txt

**Comment by greiman** [comment]
Looks like I am using a newer version of the [USB library](https://github.com/felis/USB_Host_Shield_2.0).  I downloaded the latest version and made this one line addition, `return 0;`, at about line 799 of masstorage.cpp.
```
master/masstorage.cpp" 2022-10-18 08:48:03.639503200 -0700
@@ -796,6 +796,7 @@
                 buf[i] = 0x00;
         }
         WriteOk[lun] = true;
+        return 0;  // WHG - Many USB keys don't respond to next line.  <<<<----------Line I added.
         uint8_t rc = ModeSense6(lun, 0, 0x3f, 0, 192, buf);
         if(!rc) {
                 WriteOk[lun] = ((buf[2] & 0x80) == 0);
```
A diff shows this library is identical to the one I used above.

**Comment by myslivec** [comment]
Thank you for your time. I appreciate it.
I tried the newer library but still get the error with key.begin. I will buy the same USB host module you have and give it a try. I'll let you know how it goes.

**Comment by greiman** [comment]
Be sure to add the above line.  I looked at the standard for USB mass storage and believe there is a problem with the library.

USB mass storage uses [SCSI over USB](https://en.wikipedia.org/wiki/USB_Attached_SCSI).  There are two optional commands to detect if a device is write protected.  the library only uses the older mode Sense 6 command.  There is also a Mode Sense 10 command that is newer.

Many USB keys don't respond to Mode Sense 6.  I have tried to leaving an issue years ago but no response.

**Comment by greiman** [comment]
Here is the UsbKey example I used.
[UsbKey.zip](https://github.com/greiman/UsbFat/files/9820280/UsbKey.zip)

**Comment by myslivec** [comment]
I tested [USB Host Shield](https://www.amazon.com/LM-YN-Arduino-Support-Android/dp/B0777DR3T6) with my Arduino Mega and it worked without modifying as you wrote. The problem with this [Mini USB host Shield](https://chome.nerpa.tech/mcu/usb-host-mini-hardware-manual) is in the connection SPI pins maybe. 

Thanks for your time.

**Comment by proasnet** [comment]
Hi @greiman, It working perfectly with Mega ADK, now I trying it with Mega 2560 and USB Host Shield (chinesse, not original arduino) and I get in console this
```
No USB HOST Shield?
No USB HOST Shield?
No USB HOST Shield?
No USB HOST Shield?
No USB HOST Shield?
No USB HOST Shield?
No USB HOST Shield?
No USB HOST Shield?
No USB HOST Shield?
No USB HOST Shield?
No USB HOST Shield?
No USB HOST Shield?
```
Can you think of where the problem might be?
Thank you very much

**Comment by greiman** [comment]
I have no idea.  I an not the author of the USB Host library.
