### ISSUE TITLE
Error key.begin

### ISSUE THREAD

**Issue by saikiran7714** [greiman/UsbFat#9]
sir im using your usbFat library with usb host shield but getting key.begin error . In usb host library i can get my drive information

**Comment by saikiran7714** [comment]
![presentation1](https://user-images.githubusercontent.com/41714344/43240368-bb8f8a56-90b3-11e8-960f-521468e93658.jpg)
please help me  sir....

**Comment by greiman** [comment]
I can't help.  I am no longer updating this library since it was not popular.

**Comment by greiman** [comment]
I did try the UsbDriveInfo example using an Aduino Mega ADK with a SanDisk 8 GB Cruzer Blade key.

It seems to work.

> UsbFat version: 20141220
> FreeRam 7132
> Type any character to begin
> USB initialized.
> Volume initialized.
> 
> Volume Size: 7844.90 MB (MB = 1,000,000 bytes)
> Volume is FAT32
> blocksPerCluster: 32
> clusterCount: 478815
> fatStartBlock: 742
> fatCount: 2
> blocksPerFat: 3741
> rootDirStart: 2
> dataStartBlock: 8224
> Determining free cluster count -  please wait.
> freeClusters: 471365
> freeSpace: 7722.84 MB (MB = 1,000,000 bytes)
> 
> Done
